osc-migration.md
=> Format osc-migration doc

CHANGELOG-0.x.md, docs/README.md, osc-bsu-csi-driver/values.yaml, pkg/driver/node.go, pkg/driver/node_test.go, pkg/driver/sanity_test.go, tests/e2e/stats_volume.go, tests/e2e/suite_test.go, tests/e2e/testsuites/dynamically_provisioned_stats_pod_tester.go, tests/e2e/testsuites/specs.go, tests/e2e/testsuites/testsuites.go
New feature to support NodeGetVolumeStats itf
Support full csi 1.2 interface
**What testing is done?** 
A UT + CSI SanityTest  + E2E test
=> Implement NodeGetVolumeStats

Makefile, pkg/cloud/cloud.go, tests/e2e/docker/Dockerfile_e2eTest, tests/e2e/docker/run_e2e_single_az.sh, tests/e2e/dynamic_provisioning.go, tests/e2e/pre_provsioning.go
Adapt scripts to be able to handle github ci
=> Update scripts for github ci

.github/workflows/build.yml, Makefile, hack/verify-golint
github action to validate build of osc-bsu-csi-driver projects
=> Add github build action

docs/README.md, osc-bsu-csi-driver/values.yaml
=> Update sidecar containers

Makefile, cmd/options.go, pkg/cloud/cloud.go, pkg/driver/driver.go, pkg/driver/identity.go, pkg/util/version.go, pkg/util/version_test.go
=> Set user agent in API calls

CHANGELOG-0.x.md, pkg/driver/node.go, pkg/driver/node_test.go
=> Change the default FSType

.github/workflows/cred-scan.yml, pkg/driver/validation_test.go
Also adapt random function to not trigger credential scanner.
=> Add credential leaking check

.github/workflows/e2e_test.yml
cf https://github.com/outscale-dev/cloud-provider-osc/pull/80
=> Update GH Action to test the real code

pkg/cloud/cloud.go
=> Retry on throttling errors

CHANGELOG-0.x.md, docs/README.md, docs/deploy.md, docs/development.md, docs/release.md
- Clean the documentation
- Split some parts
=> Update the documentation

.github/workflows/e2e_test.yml
Use Github action from https://github.com/outscale-dev/frieza-github-actions/
=> Clean e2e GH Action with Frieza in case of errors

.github/workflows/build.yml, Makefile
This will run trivy-scan daily and report CVE in Github security tabs
=> Add Code Scanning tool

tests/e2e/testsuites/dynamically_provisioned_stats_pod_tester.go
Before this commit, the stats were retrieved first using the metrics and
then using the df command. Sometimes, the stats could be reported as
differents because we waited 10 seconds between the two retrievals.
Now, we will try to retrieve the metrics at the same time and we will
try at most 20 times to get an equality.
=> Update logic in Stats tests

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
With Kubernetes v1.17, topology is enabled by default and the csi driver
uses external-provisioner therefore we will always have suggestions on
which zones to create the disk
closes #282
=> Default zone for CreateVolume

Dockerfile, go.mod, go.sum, pkg/driver/node.go, pkg/driver/sanity_test.go
=> Upgrade Sanity framework to test compliance to CSI spec 1.5.0

pkg/driver/node.go
=> Fix documentation links

.github/workflows/e2e_test.yml, Makefile, pkg/cloud/cloud.go
Right now, we only support "eu-west-2" in the CI
=> Adapt CI to handle different regions

.github/workflows/e2e_test.yml, .github/workflows/release.yml, Makefile, pkg/cloud/cloud.go
Some modifications of github actions has not been pushed to OSC-MIGRATION
- https://github.com/outscale-dev/osc-bsu-csi-driver/pull/340
- https://github.com/outscale-dev/osc-bsu-csi-driver/pull/317
Here is the fix
=> Cherry pick modification on master to OSC-MIGRATION

pkg/cloud/cloud.go, tests/e2e/driver/bsu_csi_driver.go, tests/e2e/dynamic_provisioning.go, tests/e2e/testsuites/specs.go
Closes #394
Add test of #394 and  #386
=> Fix ratio iops/size limit - 1.x

pkg/cloud/cloud.go, tests/e2e/driver/bsu_csi_driver.go, tests/e2e/dynamic_provisioning.go, tests/e2e/testsuites/specs.go
- Cherry-picked the fix of iops max done here https://github.com/outscale-dev/osc-bsu-csi-driver/pull/387
- Closes https://github.com/outscale-dev/osc-bsu-csi-driver/issues/394
- Add a test to avoid future regression
=> Set maximum allowed IOPS to the value accepted by Outscale - 0.x

.github/workflows/publish.yml, .github/workflows/release.yml, CHANGELOG-0.x.md
This will be added directly into the release
What is a standard changelog ? (see https://keepachangelog.com/en/1.0.0/)
=> Make the Changelog standard  for v0.x 

pkg/cloud/cloud.go
=> Adapt throttling to Outscale API - 0.x

pkg/cloud/cloud.go, pkg/cloud/utils.go, tests/e2e/dynamic_provisioning.go, tests/e2e/testsuites/testsuites.go
=> Check idempotency with API Error - 0.x

pkg/cloud/devicemanager/manager.go
This logs will allow use to confirm if the cache has some problem
=> Add log about caching mechanism when looking for deviceName - 1.x

pkg/cloud/cloud.go, pkg/cloud/utils.go, tests/e2e/dynamic_provisioning.go, tests/e2e/testsuites/testsuites.go
=> Check idempotency with API Error - 1.x

.github/workflows/build.yml, .github/workflows/e2e_test.yml
This PR is just to parallelize build CI
=> Parallelize CI

.github/workflows/release.yml
=> Upload artefact on release - 0.X

.github/workflows/e2e_test.yml, Makefile
=> Fix docker e2e test after docker upgrade

docs/helm.md, osc-bsu-csi-driver/values.yaml, pkg/cloud/devicemanager/allocator.go, pkg/driver/node.go
=> Fix name allocator osc migration

.github/workflows/action_sanity_scan.yml, .github/workflows/e2e_test.yml
=> Replace trigger e2e tests

docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/values.yaml
This PR is to add in the helmchart the following parameters:
- `leaseDuration`
- `renewDeadline`
- `retryPeriod`
=> Add leader election chart

go.mod, go.sum
=> Upgrade osc-sdk version

go.mod, go.sum
=> Update osc-sdk-go version backport

CHANGELOG-1.X.md, docs/README.md, docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/values.yaml
=> Release v1.2.2

CHANGELOG-0.x.md, docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/values.yaml
=> Release v0.2.2

docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/values.yaml, pkg/cloud/cloud.go
=> Can choose custom endpoint Backport

docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/values.yaml, pkg/cloud/cloud.go
You can choose custom endpoint
=> Can choose custom endpoint

pkg/cloud/cloud.go
Use also newConfigurationENv in newOscCloudWithoutMetadata
=> Use also newConfigurationENv in newOscCloudWithoutMetadata

CHANGELOG-0.x.md
=> Fix doc changelog backport

Dockerfile
=> Missing package xfs

Dockerfile
=> Missing package xfs Backport

docs/helm.md
=> Add helm-docs

CHANGELOG-1.X.md, docs/README.md, docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/values.yaml
=> Release-v1.2.4

CHANGELOG-0.x.md, docs/README.md, docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/values.yaml
=> Release-v0.2.4

CHANGELOG-1.X.md
=> Change type in changelog

docs/storageclass.md
=> use standard fstype

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
=> Fill SnapshotId in Disk structure - v1.X

osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/values.yaml
https://github.com/outscale/osc-bsu-csi-driver/issues/803
=> Override controler toleration

osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/values.yaml
=> Override controler toleration - v0.X

osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/templates/node.yaml
Fix for issue https://github.com/outscale/osc-bsu-csi-driver/issues/811
=> Clean way to set imagePullSecrets and respect list

osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/templates/node.yaml, osc-bsu-csi-driver/values.yaml
same (https://github.com/outscale/osc-bsu-csi-driver/pull/828)
=> Set RuntimeDefault as default seccompProfile in securityContext_0

osc-bsu-csi-driver/templates/controller.yaml
same https://github.com/outscale/osc-bsu-csi-driver/pull/826
=> Add default kube-api-qps, burst, and worker-threads values in CSI driver_0

tests/e2e/dynamic_provisioning.go
=> remove skiped test

pkg/driver/mount_test.go, pkg/driver/sanity_test.go
see https://pkg.go.dev/io/ioutil
=> replace deprecated ioutil.TempDir

osc-bsu-csi-driver/values.yaml
Same https://github.com/outscale/osc-bsu-csi-driver/pull/838
=> remove misplaced securityContext

docs/release.md
=> 📝 doc: fix version in release doc

.github/dependabot.yml
=> 👷 ci: disable dependabot on OSC-MIGRATION

.github/workflows/build.yml
=> 👷 ci: switch to official golangci-lint action

cmd/main.go, cmd/options/controller_options.go, cmd/options_test.go, docs/helm.md, osc-bsu-csi-driver/templates/_helpers.tpl, osc-bsu-csi-driver/templates/controller.yaml, osc-bsu-csi-driver/values.yaml, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go
Add extraSnapshotTags to helm chart to define custom tags added to every created snapshot
Fixes #808
=> ✨ feat: custom extra tags on snapshots

pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/driver/controller_test.go
=> 🐛 fix: recreate errored snapshots

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
* Snapshot creation is now synchronous, as per the CSI spec. The CreateSnapshot request only returns when snapshot is `completed`.
* readiness wait on resource creation now use `wait.PollUntilContextCancel` without timeout. `wait.PollUntilContextCancel` only aborts when context is cancelled (i.e. when the client aborts the request).
Fixes #789
=> ♻️ refacto: use wait.PollUntilContextCancel for wait loops, sync snaphot creation

Dockerfile, Makefile, tests/e2e/dynamic_provisioning.go, tests/e2e/suite_test.go, tests/e2e/testsuites/dynamically_provisioned_stats_pod_tester.go
=> 🐛 fix: missing xfs_growfs binary

pkg/cloud/utils.go, pkg/driver/controller.go, pkg/driver/controller_test.go
=> 🥅 errors: properly handle quota errors/snapshots in error

Dockerfile
The CSI driver will be built using Go 1.24.
Please check the relevant option(s):
=> 👷 build: build with Go 1.24

CHANGELOG-1.X.md, docs/README.md, docs/helm.md, osc-bsu-csi-driver/Chart.yaml, osc-bsu-csi-driver/helm_test.go, osc-bsu-csi-driver/values.yaml
Bump the Helm chart & driver container versions.
Update changelog for v1.7.0.
Please check the relevant option(s):
Please describe the test strategy:
=> 🔧 helm: bump helm/driver version
