- osc-bsu-csi-driver/Chart.yaml
This bugfix PR should fix the following chart issues:
* Chart naming (it did not get renamed with its directory, and according to Helm docs these should match).
* Chart versioning (Helm is starting to get very picky about it being SemVer, starting 3.5.2).
We update Chart.yaml to fix the Chart metadata. This is mainly useful currently when using the GitHub repository as a Helm repository (with the git+https:// scheme), but we start seeing SemVer version issue with Helm 3.5.2 even when using "helm template" directly.
* Naming update to `osc-bsu-csi-driver`: This permits fixing the output of "helm search repo" to actually have the correct name.
* Chart version is updated to a separate version scheme …
> Chart fixes

- .github/dependabot.yml
Signed-off-by: Ubuntu <outscale@ip-10-9-21-69.eu-west-2.compute.internal>
> add automatic alert and bump versions bot

- .trivyignore
[CVE-2022-23852](https://security-tracker.debian.org/tracker/CVE-2022-23852)
[CVE-2022-23990](https://security-tracker.debian.org/tracker/CVE-2022-23990)
> CVE libexpat

- .trivyignore
- Dockerfile
- Fixes cves: CVE-2022-0778
- Ignore for now: CVE-2021-3737
> Update Docker images

- .trivyignore
- Dockerfile
- upgrade GZIP and liblzma5
- remove the CVE from trivy-ignore
> Fixed gzip CVE (CVE-2022-1271)

- .github/workflows/build.yml
- .github/workflows/e2e_test.yml
- Build CI action needs to be execute only when source file, docker file
are modified
- e2e tests needs to be modified only when source file, docker file and
tests files are modified
> Skip CI when no important files are modified

- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
For some clusters (like OpenShift 4.X), the meta-data server is not reachable, here is a PR to partially avoid requiring an access to meta-data server.
The controller only needs the meta-data server in order to retrieve the region of the cluster to create Volume in the good region.
Now, if you provide the region during the deployment with `--region=OSC_REGION`, the controller pod will not require this access.
/!\ Note that the node pod still needs this access to retrieve its VmId.
> Remove metadata svc in controller

- .github/workflows/build.yml
- .github/workflows/cred-scan.yml
- .github/workflows/e2e_test.yml
- .github/workflows/release.yml
- Makefile
With label migration task, we need to maintain two branches therefore the GH must be updated to take that into account.
- the CI must be executed for PR into OSC-MIGRATION and master
- the CI must use as many Make commands as possible 
/!\ Skipped the Ci because it will not take into account the changes
> Update GH for label migration branch

- pkg/cloud/cloud.go
Bug fix - fixes https://github.com/outscale-dev/osc-bsu-csi-driver/issues/386
**What testing is done?** 
Built a new image and pushed to dockerhub as `pavloos/osc-bsu-csi-driver:fix-maxIops`, deployed it with helm chart and confirmed it working with below 
```
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
- key: topology.bsu.csi.outscale.com/zone
values:
- cloudgouv-eu-west-1a
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: osc-io1-big
parameters:
iopsPerGB: "300"
type: io1
provisioner: bsu.csi.outscale.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: block-claim
spec:
accessModes:
- …
```
> Set maximum allowed IOPS to the value accepted by Outscale

- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
- pkg/cloud/devicemanager/manager.go
- pkg/cloud/devicemanager/manager_test.go
The call was not idempotent because we call the API for device that are not attached.
> Fix idempotency of ControllerUnpublishVolume for 0.X

- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
- pkg/cloud/devicemanager/manager.go
- pkg/cloud/devicemanager/manager_test.go
The call was not idempotent because we call the API for device that are not attached.
> Fix idempotency of ControllerUnpublishVolume for 1.X

- .github/workflows/e2e_test.yml
The first version of `setup-helm` does not retrieve the latest version of `helm` and CI fails.
> Set the version of helm to use in e2e - 0.X

- .github/workflows/e2e_test.yml
The first version of `setup-helm` does not retrieve the latest version of `helm` and CI fails.
> Set the version of helm to use in e2e - 1.X

- .github/workflows/release.yml
For RKE2, we need the archive of the helm.
Closes #623
> Upload artefact on release - 1.X

- .github/workflows/e2e_test.yml
- Makefile
This PR is for fixing build of docker after last upgrade of runner 
See https://github.com/outscale-mdr/osc-bsu-csi-driver/actions/runs/4405177787/jobs/7783208526
⚠️ The CI will fail because we have modified the GH Action
> Fix E2E test after runner Docker upgrade

- .github/workflows/e2e_test.yml
- Makefile
Previous PR (#653) did not fix all the issu. We also need to change the build of e2e tests images
See https://github.com/outscale-mdr/osc-bsu-csi-driver/actions/runs/4437418122/jobs/7787082096
> Fix docker e2e test after docker upgrade

- docs/helm.md
- go.mod
- go.sum
- pkg/driver/node.go
- pkg/driver/node_test.go
Bug
To be able to mount 39 volumes per node for scsi device
And to solved for example:
```
2023-05-24T04:02:26Z : Warning : FailedMount : MountVolume.MountDevice failed for volume "pvc-5b47b495-a962-47cb-9deb-4962fb6f7a3b" : rpc error: code = Internal desc = Failed to find device path /dev/xvdaa. scsi path "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_sda" not found
```
**What testing is done?** 
Unit test
> Handle 39 volumes for scsi device

- docs/helm.md
- osc-bsu-csi-driver/templates/controller.yaml
- osc-bsu-csi-driver/values.yaml
Backport this PR (https://github.com/outscale/osc-bsu-csi-driver/pull/761)
> Backport feature proxy https

- osc-bsu-csi-driver/templates/controller.yaml
- osc-bsu-csi-driver/values.yaml
feature
Allow osc ccm to manipulate osc api through an https proxy when k8s cluster is not directly exposed on internet.
**What testing is done?** 
Tested with a rke2 cluster on Osc with no direct access to internet (use a squid proxy to make calls to osc api).
Mirror of the PR https://github.com/outscale/cloud-provider-osc/pull/317 for the CSI driver
> Configure https proxy + ca bundle

- pkg/driver/controller.go
- pkg/driver/controller_test.go
- pkg/driver/driver.go
This PR aims to support standard topology key `topology.kubernetes.io/zone`.
Closes #447
> Be able to use official topology

- docs/helm.md
- osc-bsu-csi-driver/Chart.yaml
- osc-bsu-csi-driver/templates/controller.yaml
- osc-bsu-csi-driver/values.yaml
> Add leader election chart master

- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
This PR is to fix a bug o idempotency in `CreateVolume` call. Indeed, if another call is submited with the same parameter with snapshotId, the second call with failed with an error.
```
E0117 17:39:32.587993       1 driver.go:112] GRPC error: rpc error: code = AlreadyExists desc = Volume already exists, but was restored from a different snapshot than snap-XXXX
```
All calls **must** be idempotent therefore this is necessary in order not to be stuck
Test of the cloud Call have been added to detect any future regression on this.
> Fill SnapshotId in Disk structure - v0.X

- osc-bsu-csi-driver/templates/controller.yaml
- osc-bsu-csi-driver/values.yaml
It can be a bug fix or a new feature, it's up to you to decide how to name it.
What?
When i want to enable a feature gate and specify it to be used by the provisioner, everytime i need to deploy the helm chart then edit the csi-controller deployment by adding the args needed.
```
- name: csi-provisioner
image: registry.k8s.io/sig-storage/csi-provisioner:v3.0.0
args:
- '--csi-address=$(ADDRESS)'
- '--feature-gates=Topology=true'
- '--feature-gates=Key=Value'
```
Why?
To make it possible for users to  controll which extra feature gates or extra arguments in general to enable using the helm chart, without the need of doing that manually after the deployment everytime. …
> add support for multiple feature-gates arguments for the csi-provisioner

- docs/helm.md
- osc-bsu-csi-driver/templates/clusterrole-attacher.yaml
- osc-bsu-csi-driver/templates/clusterrole-provisioner.yaml
- osc-bsu-csi-driver/templates/clusterrole-resizer.yaml
- osc-bsu-csi-driver/templates/clusterrole-snapshotter.yaml
- osc-bsu-csi-driver/templates/controller.yaml
- osc-bsu-csi-driver/values.yaml
This PR introduces the ability to pass custom additional arguments to the sidecar containers for the provisioner, attacher, resizer, and snapshotter controllers. This change aims to enhance the flexibility and configurability of the controllers (https://github.com/outscale/osc-bsu-csi-driver/issues/809) 
According to this PR and to enable CrossNamespaceVolumeDataSource and this documentation. https://kubernetes-csi.github.io/docs/cross-namespace-data-sources.html 
We have to enable CrossNamespaceVolumeDataSource [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) for the kube-apiserver and kube-controller-manager ( example in [osc rke k8s cluster
](https://github.com/outscale/osc-k8s-rke-cluster)
We have to : 
1. Locate the cluster …
> Fix extra arg

- osc-bsu-csi-driver/templates/controller.yaml
Is this a bug fix or adding new feature?
Improvement
What is this PR about? / Why do we need it?
Today, the max backoff period for any sidecar RPC is 5 minutes. This is problematic if the user has a misconfigured K8s object (such as invalid IOPS for volume type) because the invalid request will be retried every 5 minutes until user resolves the issue.
> Increase default provisioner, resizer, snapshotter retry-interval-max

- osc-bsu-csi-driver/templates/controller.yaml
- osc-bsu-csi-driver/templates/node.yaml
- osc-bsu-csi-driver/values.yaml
What type of PR is this?
/kind feature
What this PR does / why we need it:
feat: enable securityContext.seccompProfile
refer to https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads
What is Seccomp ?
Seccomp stands for secure computing mode and has been a feature of the Linux kernel since version 2.6.12. It can be used to sandbox the privileges of a process, restricting the calls it is able to make from userspace into the kernel. Kubernetes lets you automatically apply seccomp profiles loaded onto a node to your Pods and containers.
As a beta feature, you can configure Kubernetes to use the profile that the container runtime prefers by default
https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the …
> Set RuntimeDefault as default seccompProfile in securityContext

- osc-bsu-csi-driver/templates/controller.yaml
For context : https://docs.google.com/document/d/1wyq_9-EFsr7U90JMYXOHxoJlChwWXJqWsah3ctmuDDo/edit?tab=t.0
Added values: 
--kube-api-qps
* helps throttle the rate at which the CSI driver interacts with the Kubernetes API. If the provisioner is making too many API requests, this can overwhelm the API server, leading to performance degradation.
* Default Value: Kubernetes components usually have a default QPS value (e.g., 5 or 10). However, for high-performance workloads, a higher value is often set.
=> Setting --kube-api-qps=20 means that the CSI driver can send up to 20 requests per second to the API server.
--kube-api-burst:
* Definition: This flag controls how many API requests can be sent in a short burst. It defines the burst rate of …
> Add default kube-api-qps, burst, and worker-threads values in CSI driver

- osc-bsu-csi-driver/values.yaml
After adding the `securityContext` to both the controller and node, the pod was no longer able to mount or access the LUKS-encrypted volumes. This issue was traced to restrictive security settings that prevented necessary operations such as mounting, decrypting, and interacting with the LUKS-encrypted block devices.
The restrictive security context blocked certain operations required by the CSI driver or the pod itself to manage the encrypted volumes. In particular, settings like `allowPrivilegeEscalation: false` and `seccompProfile: RuntimeDefault` were blocking essential system calls or preventing the pod from escalating privileges when needed.
To resolve the issue, the following changes were applied:
- Set `privileged: true` to allow full access to host resources for managing encrypted …
> fix PV will be encrypted failing due to restictive securityContext

- osc-bsu-csi-driver/values.yaml
**Is this a bug fix **
Key Changes and Clarifications:
- I removed the duplicate serviceAccount block, keeping only one instance with controller and snapshot annotations.
- I removed misplacement of containerSecurityContext:
The containerSecurityContext is applied correctly under the node section and the sidecars (like provisioner, 
attacher, etc.). The serviceAccount block should not contain any security context, as it is only responsible for 
ServiceAccount metadata.
> remove duplicate sc and misplaced containerSecurityContext

- docs/README.md
See https://github.com/outscale/osc-bsu-csi-driver/issues/790
> add kernel Minimum Requirements for XFS Support

- .gitignore
- cmd/options.go
- go.mod
- go.sum
- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
- pkg/cloud/devicemanager/manager.go
- pkg/cloud/logging.go
- pkg/cloud/metadata.go
- pkg/driver/controller.go
- pkg/driver/driver.go
- pkg/driver/logging.go
- pkg/util/util.go
- tests/e2e/dynamic_provisioning.go
- ensure that verbosity is honored on most messages
- disable debug mode on Outscale client to avoid logging auth headers and reduce log volume
- tag all logs linked to a request with some request info (request type, a shared span_id, resource ids, ...)
- fix some linter errors
> 🔊 logs: migrate to structured/contextual logging

- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
waitForVolume only waits 1 minute for a volume to be available. It may take more than that, and that breaks e2e tests.
A future PR will properly handle timeouts and requests aborts for server calls.
> 💚 fix: use backoff in waitForVolume to fix e2e test failures

- pkg/cloud/backoff.go
- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
- pkg/cloud/logging.go
- pkg/driver/controller_test.go
- tests/e2e/dynamic_provisioning.go
- tests/e2e/pre_provisioning.go
Tests and production may have different requirements re. OAPI calls backoff. This allows setting a custom backoff policy. The default policy also backoffs on additional 5XX errors.
> ✨ feat: support custom backoff policies

- .github/workflows/e2e_test.yml
- Dockerfile
- Makefile
- docs/README.md
- docs/troubleshooting.md
Image is based on a static distroless base image. The debug variant is used, it includes busybox to enable shell access to the pods. This saves ~40MB.
The Go binary is stripped, saving ~20MB.
Image size is reduced from 121MB to 63MB.
> ⬆️ deploy: switch to distroless image, strip binary

- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
Fixes an infinite loop when the number of snapshots was over the page size
> 🐛 fix: fix pagination on ListSnapshots

- docs/deploy.md
- pkg/cloud/backoff.go
- pkg/cloud/backoff_test.go
- pkg/cloud/cloud.go
- pkg/cloud/cloud_test.go
- pkg/util/util.go
When the controller aborts a request (e.g. due to a timeout), context is cancelled. No need to continue the request, the controller will retry.
> 🐛 fix: stop backoff when context is cancelled

- .github/workflows/build.yml
Trivy was disabled because it did not support the old Alpine base image. Now that we switched to a more recent image, trivy is reenabled.
> 👷 ci: enable trivy

- .github/workflows/build.yml
On OSC-MIGRATION:
* lint errors will not be corrected on branch OSC-MIGRATION => disabling failing linter step (make verify)
* helm doc is not updated => no need to check it
* trivy does not support the old Alpine base image => disabling
> 👷 ci: disable broken ci on OSC-MIGRATION

- docs/helm.md
- osc-bsu-csi-driver/helm_test.go
- osc-bsu-csi-driver/values.yaml
- pkg/cloud/metadata.go
- pkg/cloud/metadata_test.go
- pkg/driver/mocks/mock_metadata_service.go
- pkg/driver/node.go
- pkg/driver/node_test.go
- pkg/driver/sanity_test.go
There is a limit of 40 volumes per VM (including the root volume, which means 39 additional volumes).
This limit includes:
* volumes mounted by the OS at boot,
* volumes mounted by the CSI.
Previously, the code always returned 39 available volumes, without accounting for volumes mounted by the OS.
This PR computes the actual number of volumes.
Ideally, we would call OAPI to retrieve the list of attached volumes, but this would require the node controller to have access to OAPI.
The computation is performed at startup, any volume mounted afterward is not taken into account.
> ✨ feat: automatically compute maxBsuVolumes

- tests/e2e/dynamic_provisioning.go
Add a test with 39 volumes (the max number of BSU volumes that can be attached to a VM) attached to a single pod.
Please check the relevant option(s):
Please describe the test strategy:
> ✅ e2e: add 39 volumes test
